### ISSUE TITLE
"No Provider For ViewContainerRef" in NotificationService

### ISSUE THREAD

**Issue by maahtiin** [carbon-design-system/carbon-components-angular#2716]
## Detailed description

Using the latest carbon-components-angular v5.14.11 with Angular v14.3.0.
When using the NotificationService (i.e. referring to `showNotification()` method), the UI fails to load. It shows the stacktrace referenced below.

This did not occur in 5.1.0.

## Additional information

```
Unhandled Promise rejection: NullInjectorError: No provider for ViewContainerRef! ; Zone: <root> ; Task: Promise.then ; Value: NullInjectorError: NullInjectorError: No provider for ViewContainerRef!
    at NullInjector.get (core.mjs:8191:27)
    at R3Injector.get (core.mjs:8618:33)
    at R3Injector.get (core.mjs:8618:33)
    at R3Injector.get (core.mjs:8618:33)
    at injectInjectorOnly (core.mjs:4782:33)
    at Module.ɵɵinject (core.mjs:4786:12)
    at Object.NotificationService_Factory [as factory] (carbon-components-angular-notification.mjs:856:1)
    at R3Injector.hydrate (core.mjs:8719:35)
    at R3Injector.get (core.mjs:8607:33)
    at injectInjectorOnly (core.mjs:4782:33) NullInjectorError: NullInjectorError: No provider for ViewContainerRef!
    at NullInjector.get (http://dev.local/vendor.js:484509:21)
    at R3Injector.get (http://dev.local/vendor.js:485012:27)
    at R3Injector.get (http://dev.local/vendor.js:485012:27)
    at R3Injector.get (http://dev.local/vendor.js:485012:27)
    at injectInjectorOnly (http://dev.local/vendor.js:480533:29)
    at Module.ɵɵinject (http://dev.local/vendor.js:480538:59)
    at Object.NotificationService_Factory [as factory] (http://dev.local/vendor.js:562600:204)
    at R3Injector.hydrate (http://dev.local/vendor.js:485126:29)
    at R3Injector.get (http://dev.local/vendor.js:485002:23)
    at injectInjectorOnly (http://dev.local/vendor.js:480533:29)
```

**Comment by ashishpawar12** [comment]
Is there any update for this issue. I am also facing same error.

**Comment by maahtiin** [comment]
No update yet. If i find anything, i'll make sure to let you know.
